### ISSUE TITLE
I encounter this error when using the ImageGeneration-py script. Has anyone solved it? Meanwhile, there is not a single file in my output folder

### ISSUE THREAD

**Issue by Monica-tt** [VulCNN/VulCNN#27]
unlink: cannot unlink '/dev/shm/s2v_data_model_input_matrix.init': No such file or directory
unlink: cannot unlink '/dev/shm/s2v_data_model_input_matrix': No such file or directory

**Comment by Byw111** [comment]
> unlink: cannot unlink '/dev/shm/s2v_data_model_input_matrix.init': No such file or directory unlink: cannot unlink '/dev/shm/s2v_data_model_input_matrix': No such file or directory

please，how did you solve it

**Comment by Leehouc** [comment]
I encounter this error today, and dont know what to do

**Comment by txg666** [comment]
> I encounter this error today, and dont know what to do



> > unlink: cannot unlink '/dev/shm/s2v_data_model_input_matrix.init': No such file or directory unlink: cannot unlink '/dev/shm/s2v_data_model_input_matrix': No such file or directory
> 
> please，how did you solve it

Just comment out the line 'sent2vec_madel. relese_sthared_mem (trained_madel_math)'! If no pkl is generated later, it may be due to the lack of the "pydot" package, just install it through pip.

**Comment by txg666** [comment]
> I encounter this error today, and dont know what to do

Just comment out the line 'sent2vec_madel. relese_sthared_mem (trained_madel_math)'! If no pkl is generated later, it may be due to the lack of the "pydot" package, just install it through pip.
