### ISSUE TITLE
The accuracy  is fixed, has anyone been in the same situation?because the .dot file is in the folder,makes the program cannot find .dot。But if i change it to the code at below,it still dont work

### ISSUE THREAD

**Issue by Byw111** [VulCNN/VulCNN#28]
for root, dirs, files in os.walk(dir_name):
        for file in files:
            if root[-1] == '/':
                root = root
            else:
                root += "/"
            dotfiles = glob.glob(root + '*.dot')
<img width="896" alt="屏幕截图 2024-10-25 163641" src="https://github.com/user-attachments/assets/df603fe5-7c0c-46a2-8315-72b34c3b4b42">

**Comment by Byw111** [comment]
Found the reason, it's the dot file I generated: the graph is empty

**Comment by huangyuyan3** [comment]
> Found the reason, it's the dot file I generated: the graph is empty

Could you tell me if the effect achieved after your solution is consistent with the results stated in the paper?

**Comment by Byw111** [comment]
> > Found the reason, it's the dot file I generated: the graph is empty
> 
> Could you tell me if the effect achieved after your solution is consistent with the results stated in the paper?

yes，and the acc higher。
